[package]
authors = ["Simpa"]
name = "Rustymemo"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
clap = { version = "4.5.4", features = ["derive"] }
tui = "0.19.0"
crossterm = "0.29.0"
fuzzy-matcher = "0.3.7"
